### ISSUE TITLE
Probeer hier geen inline style te gebruiken

### ISSUE THREAD

**Issue by KrijnHoetmer** [Keremttc/fix-the-flow-interactive-website#3]
Maar kijk eens naar de `classList.toggle()` van afgelopen woensdag. Of in dit geval de [hidden property](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden).

https://github.com/Keremttc/fix-the-flow-interactive-website/blob/08ea8725aece6b8c941015fb38f396887a65750f/myscripts.js#L20

**Comment by Kerem-Tutucu** [comment]
done

**Comment by KrijnHoetmer** [comment]
Nog niet gepushed denk ik?

Probeer volgende keer issues te sluiten via je commits. Dan hoef je het niet handmatig te doen, dan worden ze pas gesloten zodra je ze naar GitHub pusht, en dan ziet de persoon die het issue ingeschoten heeft meteen wat je precies veranderd hebt. Nu is het nogal onduidelijk..
