### ISSUE TITLE
Event handler op niet-interactieve elementen

### ISSUE THREAD

**Issue by KrijnHoetmer** [Keremttc/fix-the-flow-interactive-website#4]
Zet je event handlers altijd op interactieve elementen, zodat ze (bijvoorbeeld) ook werken met het toetsenbord (Sprint 3). Test je werk dus ook op Toegankelijkheid.

https://github.com/Keremttc/fix-the-flow-interactive-website/blob/08ea8725aece6b8c941015fb38f396887a65750f/index.html#L20

**Comment by Kerem-Tutucu** [comment]
https://github.com/Keremttc/fix-the-flow-interactive-website/blob/main/index.html#L18 

aangepast

**Comment by KrijnHoetmer** [comment]
Nou nog doorpakken met #2 :)
